import type { ProfileSection } from "@types";

export const PROFILE_MENU_SECTIONS: ProfileSection[] = [
  {
    id: "preferences",
    title: "Preferences",
    items: [
      {
        id: "theme",
        title: "Theme",
        subtitle: "Auto (System)",
        icon: "palette",
        action: "navigation",
        iconColor: "#8b5cf6",
        iconBgColor: "rgba(139, 92, 246, 0.1)",
        rightContent: "arrow",
      },
      {
        id: "notifications",
        title: "Notifications",
        subtitle: "Push notifications enabled",
        icon: "bell",
        action: "toggle",
        iconColor: "#028595",
        iconBgColor: "rgba(2, 133, 149, 0.1)",
        rightContent: "switch",
      },
      {
        id: "sounds",
        title: "Sounds & Haptics",
        subtitle: "Enabled",
        icon: "volume-2",
        action: "toggle",
        iconColor: "#14b8a6",
        iconBgColor: "rgba(20, 184, 166, 0.1)",
        rightContent: "switch",
      },
    ],
  },
  {
    id: "data",
    title: "Data & Privacy",
    items: [
      {
        id: "backup",
        title: "Backup Data",
        subtitle: "Last backup: 2 days ago",
        icon: "cloud-upload",
        action: "action",
        iconColor: "#3b82f6",
        iconBgColor: "rgba(59, 130, 246, 0.1)",
        rightContent: "arrow",
      },
      {
        id: "export",
        title: "Export Data",
        subtitle: "Download your data",
        icon: "download",
        action: "action",
        iconColor: "#06b6d4",
        iconBgColor: "rgba(6, 182, 212, 0.1)",
        rightContent: "arrow",
      },
      {
        id: "privacy",
        title: "Privacy Policy",
        icon: "shield",
        action: "navigation",
        iconColor: "#10b981",
        iconBgColor: "rgba(16, 185, 129, 0.1)",
        rightContent: "arrow",
      },
    ],
  },
  {
    id: "support",
    title: "Support",
    items: [
      {
        id: "help",
        title: "Help Center",
        subtitle: "Get help and support",
        icon: "help-circle",
        action: "navigation",
        iconColor: "#f59e0b",
        iconBgColor: "rgba(245, 158, 11, 0.1)",
        rightContent: "arrow",
      },
      {
        id: "feedback",
        title: "Send Feedback",
        subtitle: "Help us improve",
        icon: "message-circle",
        action: "action",
        iconColor: "#ec4899",
        iconBgColor: "rgba(236, 72, 153, 0.1)",
        rightContent: "arrow",
      },
      {
        id: "rate",
        title: "Rate DayFlow",
        icon: "star",
        action: "action",
        iconColor: "#eab308",
        iconBgColor: "rgba(234, 179, 8, 0.1)",
        rightContent: "arrow",
      },
    ],
  },
  {
    id: "account",
    title: "Account",
    items: [
      {
        id: "logout",
        title: "Sign Out",
        icon: "log-out",
        action: "action",
        iconColor: "#ef4444",
        iconBgColor: "rgba(239, 68, 68, 0.1)",
        rightContent: "arrow",
      },
    ],
  },
];
